require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: disable
  Exclude:
    - 'app/views/**/*.slim'
    - 'bin/bundle'
    - 'vendor/**/*'

# METRICS
Metrics/MethodLength:
  CountComments: false
  Max: 15
  Exclude:
    - 'spec/**/*'
Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'spec/**/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# LAYOUT
Layout/AccessModifierIndentation:
  Enabled: false
Layout/CommentIndentation:
  Enabled: false
Layout/DotPosition:
  EnforcedStyle: leading
  Enabled: true
Layout/ExtraSpacing:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/HashAlignment:
  EnforcedHashRocketStyle: separator
  EnforcedColonStyle: table
Layout/LineLength:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false

# NAMING
Naming/VariableNumber:
  Enabled: false

# STYLE
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes

# RAILS
Rails/Output:
  Exclude:
    - 'app/services/stdout_reporter.rb'

# RSPEC
RSpec/ContextWording:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Max: 5
RSpec/MultipleExpectations:
  Max: 5
