version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

defaults: &defaults
  working_directory: ~/scbreakpoints

ruby_machine: &ruby_machine
  <<: *defaults
  docker:
    - image: circleci/ruby:2.6.6-stretch-node
    - image: circleci/mongo:4.0.20-xenial-ram
  executor: ruby/default

jobs:
  Build:
    <<: *ruby_machine
    steps:
      - checkout
      - run:
          name: Bundle install
          command: |
            gem install bundler -v='2.1.4'
            bundle install
      - run:
          name: Dockerize MongoDB
          command: dockerize -wait tcp://localhost:27017 -timeout 1m

  Test:
    <<: *ruby_machine
    requires:
      - Build
    - run:
      name: RSpec
      command: bundle exec rspec
