version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

defaults: &defaults
  working_directory: ~/scbreakpoints

ruby_machine: &ruby_machine
  <<: *defaults
  docker:
    - image: cimg/ruby:2.6.6-node
      environment:
        RAILS_ENV: test
        BUNDLE_PATH: vendor/bundle
        BUNDLER_VERSION: 2.1.4
  executor: ruby/default

jobs:
  build:
    <<: *ruby_machine
    steps:
      - checkout
      - attach_workspace:
          at: ~/scbreakpoints
      - run:
          name: SQLite install
          command: sudo apt-get update && sudo apt-get install sqlite3 libsqlite3-dev
      - run:
          name: Bundle install
          command: |
            gem install bundler -v=${BUNDLER_VERSION}
            bundle install --path=vendor/bundle
      - persist_to_workspace:
          root: ~/scbreakpoints
          paths:
            - vendor/bundle
  test:
    <<: *ruby_machine
    steps:
      - checkout
      - attach_workspace:
          at: ~/scbreakpoints
      - run:
          name: RSpec
          command: |
            gem install bundler -v=${BUNDLER_VERSION}
            bundle exec rake db:test:prepare
            bundle exec rspec

  rubocop:
    <<: *ruby_machine
    steps:
      - checkout
      - attach_workspace:
          at: ~/scbreakpoints
      - run:
          name: RuboCop
          command: |
            gem install bundler -v=${BUNDLER_VERSION}
            bundle exec rubocop


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - rubocop:
          requires:
            - build
