version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  aws-ecr: circleci/aws-ecr@8.1.2
  aws-ecs: circleci/aws-ecs@2.3.0

defaults: &defaults
  working_directory: ~/scbreakpoints

ruby_machine: &ruby_machine
  <<: *defaults
  docker:
    - image: cimg/ruby:2.6.6-node
      environment:
        RAILS_ENV: test
        BUNDLE_PATH: vendor/bundle
        BUNDLER_VERSION: 2.1.4
  executor: ruby/default

jobs:
  build:
    <<: *ruby_machine
    steps:
      - checkout
      - attach_workspace:
          at: ~/scbreakpoints
      - run:
          name: SQLite install
          command: sudo apt-get update && sudo apt-get install sqlite3 libsqlite3-dev
      - run:
          name: Bundle install
          command: |
            gem install bundler -v=${BUNDLER_VERSION}
            bundle install --path=vendor/bundle
      - persist_to_workspace:
          root: ~/scbreakpoints
          paths:
            - vendor/bundle
  test:
    <<: *ruby_machine
    steps:
      - checkout
      - attach_workspace:
          at: ~/scbreakpoints
      - run:
          name: RSpec
          command: |
            gem install bundler -v=${BUNDLER_VERSION}
            bundle exec rake db:test:prepare
            bundle exec rspec

  rubocop:
    <<: *ruby_machine
    steps:
      - checkout
      - attach_workspace:
          at: ~/scbreakpoints
      - run:
          name: RuboCop
          command: |
            gem install bundler -v=${BUNDLER_VERSION}
            bundle exec rubocop

  build_and_push_image:
    executor: docker-machine
    steps:
      - aws-ecr/build-and-push-image:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: AWS_REGION_STG
          account-url: AWS_ECR_ACCOUNT_URL
          repo: scbreakpoints
          tag: "${CIRCLE_BUILD_NUM},latest"
          dockerfile: Dockerfile
          attach-workspace: true
          workspace-root: ~/scbreakpoints

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_push_image
      - build
      - test:
          requires:
            - build
      - rubocop:
          requires:
            - build

