version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
        name: Bundle install
        command: |
          gem install bundler -v='2.1.4'
          bundle install
      - run:
        name: RSpec
        command: bundle exec rspec
