version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

defaults: &defaults
  working_directory: ~/scbreakpoints

ruby_machine: &ruby_machine
  <<: *defaults
  docker:
    - image: circleci/ruby:2.6.6-stretch-node
      environment:
        RAILS_ENV: test
        BUNDLE_PATH: $BUNDLE_PATH
        BUNDLER_VERSION: 2.1.4
    - image: circleci/mongo:4.0.20-xenial-ram
  executor: ruby/default

jobs:
  build:
    <<: *ruby_machine
    steps:
      - checkout
      - attach_workspace:
          at: ~/scbreakpoints
      - run:
          name: Bundle install
          command: |
            gem install bundler -v=$BUNDLER_VERSION
            bundle install --path=$BUNDLE_PATH
      - persist_to_workspace:
          root: ~/scbreakpoints
          paths:
            - $BUNDLE_PATH
  test:
    <<: *ruby_machine
    steps:
      - checkout
      - attach_workspace:
          at: ~/scbreakpoints
      - run:
          name: RSpec
          command: |
            gem install bundler -v=$BUNDLER_VERSION
            bundle exec rspec

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
