development:
  clients:
    default:
      # database: scbreakpoints-dev
      uri: mongodb+srv://<uri>
      # hosts:
        # - <%= ENV['MONGO_HOST'] %>:27017
      options:
        server_selection_timeout: 5
        # password: <%= ENV['MONGO_PASSWORD'] %>
        # user: <%= ENV['MONGO_USERNAME'] %>
        # auth_source: admin

test:
  clients:
    default:
      database: scbreakpoints-test
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1

production:
  clients:
    default:
      database: scbreakpoints
      hosts:
        - <%= ENV['MONGO_HOST'] %>:27017
      options:
        server_selection_timeout: 1
        password: <%= ENV['MONGO_PASSWORD'] %>
        user: <%= ENV['MONGO_USERNAME'] %>
        auth_source: admin
