development:
  clients:
    default:
      database: scbreakpoints-dev
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1

test:
  clients:
    default:
      database: scbreakpoints-test
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1
